version: '3'
services:
  node-app:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

  react-app:
    build:
      context: ./server
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
